#!/usr/bin/env bash

if [ -f "/root/.composer/vendor/acquia/blt/blt.sh" ]; then
  /root/.composer/vendor/acquia/blt/blt.sh "$@"
else
  echo "You must run this command from within a BLT-generated project repository."
fi
