#!/usr/bin/env bash

if [ "`git rev-parse --show-cdup 2> /dev/null`" != "" ]; then
  GIT_ROOT=$(git rev-parse --show-cdup)
else
  GIT_ROOT="."
fi

if [ -f "$GIT_ROOT/vendor/bin/blt" ]; then
  $GIT_ROOT/vendor/bin/blt "$@"
else
  ln -s /root/.composer/vendor $GIT_ROOT/vendor
  $GIT_ROOT/vendor/bin/blt "$@"
fi

